# Generated by Django 4.1.5 on 2023-01-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car_id',
            new_name='car',
        ),
    ]
